USE [master]
GO

/****** Object:  Database [HW3]    Script Date: 2/18/2019 6:19:48 PM ******/
CREATE DATABASE [HW3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HW3', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\HW3.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HW3_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\HW3_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HW3] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HW3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HW3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HW3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HW3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HW3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HW3] SET ARITHABORT OFF 
GO

ALTER DATABASE [HW3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HW3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HW3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HW3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HW3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HW3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HW3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HW3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HW3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HW3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HW3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HW3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HW3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HW3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HW3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HW3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HW3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HW3] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HW3] SET  MULTI_USER 
GO

ALTER DATABASE [HW3] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HW3] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HW3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HW3] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HW3] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HW3] SET  READ_WRITE 
GO

